[package]
authors = ["Le Duc Pham <duc@orai.io>"]
edition = "2018"
name = "oscript_basic"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true
panic = 'abort'
rpath = false

[dependencies]

cosmwasm-std = {version = "0.13.2", features = ["iterator"]}
cosmwasm-storage = {version = "0.13.2", features = ["iterator"]}
schemars = "0.7"
serde = {version = "1.0.103", default-features = false, features = ["derive"]}
thiserror = {version = "1.0.20"}

[dev-dependencies]
cosmwasm-schema = {version = "0.13.2"}
